In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/life-expectancy-who/Life Expectancy Data.csv

In [2]:
import pandas as pd

data = pd.read_csv("/kaggle/input/life-expectancy-who/Life Expectancy Data.csv")
# Convert to DataFrame
df = pd.DataFrame(data)

df.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

In [3]:
df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [4]:
# Strip spaces from column names
df.columns = df.columns.str.strip()
# Replace spaces with underscores
df.columns = [col.replace(" ", "_") for col in df.columns]
df.columns = ['Country', 'Year', 'Status', 'Life_expectancy', 'Adult_Mortality',
       'infant_deaths', 'Alcohol', 'percentage_expenditure', 'Hepatitis_B',
       'Measles', 'BMI', 'under_five_deaths', 'Polio', 'Total_expenditure',
       'Diphtheria', 'HIV_AIDS', 'GDP', 'Population', 'thinness_1_19_years',
       'thinness_5_9_years', 'Income_composition_of_resources', 'Schooling']
# Verify cleaned column names
print(df.columns)

Index(['Country', 'Year', 'Status', 'Life_expectancy', 'Adult_Mortality',
       'infant_deaths', 'Alcohol', 'percentage_expenditure', 'Hepatitis_B',
       'Measles', 'BMI', 'under_five_deaths', 'Polio', 'Total_expenditure',
       'Diphtheria', 'HIV_AIDS', 'GDP', 'Population', 'thinness_1_19_years',
       'thinness_5_9_years', 'Income_composition_of_resources', 'Schooling'],
      dtype='object')

In [5]:
print(df['Year'].max())
print(df['Year'].min())
print(df['Country'].unique())
print(df['Status'].unique())

2015
2000
['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Antigua and Barbuda'
 'Argentina' 'Armenia' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas'
 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin'
 'Bhutan' 'Bolivia (Plurinational State of)' 'Bosnia and Herzegovina'
 'Botswana' 'Brazil' 'Brunei Darussalam' 'Bulgaria' 'Burkina Faso'
 'Burundi' "Côte d'Ivoire" 'Cabo Verde' 'Cambodia' 'Cameroon' 'Canada'
 'Central African Republic' 'Chad' 'Chile' 'China' 'Colombia' 'Comoros'
 'Congo' 'Cook Islands' 'Costa Rica' 'Croatia' 'Cuba' 'Cyprus' 'Czechia'
 "Democratic People's Republic of Korea"
 'Democratic Republic of the Congo' 'Denmark' 'Djibouti' 'Dominica'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'Equatorial Guinea'
 'Eritrea' 'Estonia' 'Ethiopia' 'Fiji' 'Finland' 'France' 'Gabon' 'Gambia'
 'Georgia' 'Germany' 'Ghana' 'Greece' 'Grenada' 'Guatemala' 'Guinea'
 'Guinea-Bissau' 'Guyana' 'Haiti' 'Honduras' 'Hungary' 'Iceland' 'India'
 'Indonesia' 'Iran (Islamic Republic of)' 'Iraq' 'Ireland' 'Israel'
 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati'
 'Kuwait' 'Kyrgyzstan' "Lao People's Democratic Republic" 'Latvia'
 'Lebanon' 'Lesotho' 'Liberia' 'Libya' 'Lithuania' 'Luxembourg'
 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta'
 'Marshall Islands' 'Mauritania' 'Mauritius' 'Mexico'
 'Micronesia (Federated States of)' 'Monaco' 'Mongolia' 'Montenegro'
 'Morocco' 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands'
 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'Niue' 'Norway' 'Oman'
 'Pakistan' 'Palau' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru'
 'Philippines' 'Poland' 'Portugal' 'Qatar' 'Republic of Korea'
 'Republic of Moldova' 'Romania' 'Russian Federation' 'Rwanda'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Vincent and the Grenadines'
 'Samoa' 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal'
 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia'
 'Solomon Islands' 'Somalia' 'South Africa' 'South Sudan' 'Spain'
 'Sri Lanka' 'Sudan' 'Suriname' 'Swaziland' 'Sweden' 'Switzerland'
 'Syrian Arab Republic' 'Tajikistan' 'Thailand'
 'The former Yugoslav republic of Macedonia' 'Timor-Leste' 'Togo' 'Tonga'
 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan' 'Tuvalu' 'Uganda'
 'Ukraine' 'United Arab Emirates'
 'United Kingdom of Great Britain and Northern Ireland'
 'United Republic of Tanzania' 'United States of America' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Venezuela (Bolivarian Republic of)' 'Viet Nam'
 'Yemen' 'Zambia' 'Zimbabwe']
['Developing' 'Developed']

In [6]:

# Fill missing values for textual columns with "unknown"
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].fillna("unknown")

In [7]:
import sqlite3

# Create SQLite database
conn = sqlite3.connect("database_life_exp.db")

df.to_sql('Life_Expectancy', conn, if_exists="replace", index=False)

conn.close()

In [8]:
# testing the database.
conn = sqlite3.connect("database_life_exp.db")
cursor = conn.cursor()

# Example: Query data
cursor.execute("SELECT * FROM 'Life_expectancy' LIMIT 5;")
rows = cursor.fetchall()

# Print the rows
for row in rows:
    print(row)
conn.close()

('Afghanistan', 2015, 'Developing', 65.0, 263.0, 62, 0.01, 71.27962362, 65.0, 1154, 19.1, 83, 6.0, 8.16, 65.0, 0.1, 584.25921, 33736494.0, 17.2, 17.3, 0.479, 10.1)
('Afghanistan', 2014, 'Developing', 59.9, 271.0, 64, 0.01, 73.52358168, 62.0, 492, 18.6, 86, 58.0, 8.18, 62.0, 0.1, 612.696514, 327582.0, 17.5, 17.5, 0.476, 10.0)
('Afghanistan', 2013, 'Developing', 59.9, 268.0, 66, 0.01, 73.21924272, 64.0, 430, 18.1, 89, 62.0, 8.13, 64.0, 0.1, 631.744976, 31731688.0, 17.7, 17.7, 0.47, 9.9)
('Afghanistan', 2012, 'Developing', 59.5, 272.0, 69, 0.01, 78.1842153, 67.0, 2787, 17.6, 93, 67.0, 8.52, 67.0, 0.1, 669.959, 3696958.0, 17.9, 18.0, 0.463, 9.8)
('Afghanistan', 2011, 'Developing', 59.2, 275.0, 71, 0.01, 7.097108703, 68.0, 3013, 17.2, 97, 68.0, 7.87, 68.0, 0.1, 63.537231, 2978599.0, 18.2, 18.2, 0.454, 9.5)

In [9]:
from typing import List
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("juierror/flan-t5-text2sql-with-schema-v2")
model = AutoModelForSeq2SeqLM.from_pretrained("juierror/flan-t5-text2sql-with-schema-v2")

tokenizer_config.json:   0%|          | 0.00/2.35k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/17.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/990M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/142 [00:00<?, ?B/s]

In [10]:

def get_prompt(tables, question):
    prompt = f"""convert question and table into SQL query. tables: {tables}. question: {question}"""
    return prompt

def prepare_input(question: str, tables: dict[str, List[str]]):
    tables = [f"""{table_name}({",".join(tables[table_name])})""" for table_name in tables]
    tables = ", ".join(tables)
    prompt = get_prompt(tables, question)
    input_ids = tokenizer(prompt, max_length=1000, return_tensors="pt",truncation=True).input_ids
    return input_ids

def inference(question: str, tables: dict[str, List[str]]) -> str:
    input_data = prepare_input(question=question, tables=tables)
    input_data = input_data.to(model.device)
    outputs = model.generate(inputs=input_data,  max_length=1000)
    result = tokenizer.decode(token_ids=outputs[0], skip_special_tokens=True)
    return result

In [11]:

# Connect to the database
conn = sqlite3.connect("database_life_exp.db")
cursor = conn.cursor()

# Replace 'Life_Expectancy' with your table name
cursor.execute("PRAGMA table_info(Life_Expectancy)")
columns = cursor.fetchall()

# Extract column names
column_names = [column[1] for column in columns]

print("Column names:", column_names)

# Close the connection
conn.close()

Column names: ['Country', 'Year', 'Status', 'Life_expectancy', 'Adult_Mortality', 'infant_deaths', 'Alcohol', 'percentage_expenditure', 'Hepatitis_B', 'Measles', 'BMI', 'under_five_deaths', 'Polio', 'Total_expenditure', 'Diphtheria', 'HIV_AIDS', 'GDP', 'Population', 'thinness_1_19_years', 'thinness_5_9_years', 'Income_composition_of_resources', 'Schooling']

In [12]:

scheme = {'Life_expectancy':['Country', 'Year', 'Status', 'Life_expectancy', 'Adult_Mortality',
       'infant_deaths', 'Alcohol', 'percentage_expenditure', 'Hepatitis_B',
       'Measles', 'BMI', 'under_five_deaths', 'Polio', 'Total_expenditure',
       'Diphtheria', 'HIV_AIDS', 'GDP', 'Population', 'thinness_1_19_years',
       'thinness_5_9_years', 'Income_composition_of_resources', 'Schooling']}

print(inference("What is the average population in Sweden", scheme))

SELECT avg(Population) FROM Life_expectancy WHERE Country = "Sweden"

In [13]:
table_desc = {'Life_expectancy':{
    'Country': 'Country',
    'Year': 'Year',
    'Status': 'Developed or Developing status',
    'Life_expectancy': 'Life Expectancy in age',
    'Adult_Mortality': 'Adult Mortality Rates of both sexes (probability of dying between 15 and 60 years per 1000 population)',
    'infant_deaths': 'Number of Infant Deaths per 1000 population',
    'Alcohol': 'Alcohol, recorded per capita (15+) consumption (in litres of pure alcohol)',
    'percentage_expenditure': 'Expenditure on health as a percentage of Gross Domestic Product per capita(%)',
    'Hepatitis_B': 'Hepatitis B (HepB) immunization coverage among 1-year-olds (%)',
    'Measles': 'Measles - number of reported cases per 1000 population',
    'BMI': 'Average Body Mass Index of entire population',
    'under_five_deaths': 'Number of under-five deaths per 1000 population',
    'Polio': 'Polio (Pol3) immunization coverage among 1-year-olds (%)',
    'Total_expenditure': 'General government expenditure on health as a percentage of total government expenditure (%)',
    'Diphtheria': 'Diphtheria tetanus toxoid and pertussis (DTP3) immunization coverage among 1-year-olds (%)',
    'HIV_AIDS': 'Deaths per 1 000 live births HIV/AIDS (0-4 years)',
    'GDP': 'Gross Domestic Product per capita (in USD)',
    'Population': 'Population of the country',
    'thinness_1_19_years': 'Prevalence of thinness among children and adolescents for Age 10 to 19 (%)',
    'thinness_5_9_years': 'Prevalence of thinness among children for Age 5 to 9 (%)',
    'Income_composition_of_resources': 'Human Development Index in terms of income composition of resources (index ranging from 0 to 1)',
    'Schooling': 'Number of years of Schooling (years)'}
}

In [14]:
from fuzzywuzzy import fuzz
from fuzzywuzzy import process


def get_closest_country(input_country, country_list):
    # Find the closest match to the input country from the country list
    best_match = process.extractOne(input_country, country_list)
    return best_match[0]  # Return the closest country name

def extract_data(sql):
    # From the genereated SQL retrieve the data and return both data and SQL query
    conn = sqlite3.connect("database_life_exp.db")
    cursor = conn.cursor() # open database

    # try the sql call
    try:
        if 'Country =' in sql: # Extract country from the SQL query (if applicable)
            cursor.execute("SELECT DISTINCT Country FROM Life_Expectancy")
            countries = [row[0] for row in cursor.fetchall()] # all countries in the data

            start = 0
            while 'Country = "' in sql[start:]:
                # Find the start and end of the current country in the SQL string
                country_start = sql.find('Country = "', start) + len('Country = "')
                country_end = sql.find('"', country_start)
                
                # Extract the misspelled country
                misspelled_country = sql[country_start:country_end]
                
                # Correct the country name
                correct_country = get_closest_country(misspelled_country, countries)
                
                # Replace the misspelled country with the corrected one
                sql = sql[:country_start] + correct_country + sql[country_end:]
                
                # Update the start position for the next occurrence
                start = country_end
            
        cursor.execute(sql) 
        rows = cursor.fetchall()
        
        # Check if rows are empty or contain only (None,)
        if rows == [(None,)]:
            rows = 'No data found for the query.'
        
    except Exception as e:
        print(f"Error: {e}") 
        rows  = 'The SQL query didnt go through'
    finally:
        conn.close()

    return sql,rows # return the sql and fetched data

/opt/conda/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [15]:
conn = sqlite3.connect("database_life_exp.db")
cursor = conn.cursor() # open database
print(cursor.execute('SELECT avg(Population) FROM Life_expectancy WHERE Country = "Sweden"').fetchall())
conn.close()

[(5514868.3125,)]

In [16]:
# Example query
query = "What is the average life expectancy in Sweden?"

query_res= inference(query, scheme)

print(extract_data(query_res))

('SELECT avg(Life_expectancy) FROM Life_expectancy WHERE Country = "Sweden"', [(82.51875,)])

In [17]:
# Example query
query = "What is the populations in United Kingdom in year 2015?"

import time    # this is an inbuilt library in Python

start_time = time.time()
query_res= inference(query, scheme)
end_time = time.time()
print("Execution time: ", end_time - start_time,"secs")
print(extract_data(query_res))

Execution time:  1.9455721378326416 secs
('SELECT Population FROM Life_expectancy WHERE Country = "United Kingdom of Great Britain and Northern Ireland" AND YEAR = 2015', 'No data found for the query.')

In [18]:
# Example query
query = "What was the Gross domestic product in France in Year 2005?"

query_res= inference(query, scheme)

print(extract_data(query_res))

('SELECT GDP FROM Life_expectancy WHERE Country = "France" AND YEAR = 2005', [(34879.72633,)])

In [19]:
# creating questions to test the retriever 
# The same questions will be used when evaluating the generator
# So I've added them too

Questions = [
    {
        "Question": "What was the Gross Domestic Product in France in the year 2005?",
        "SQL":"SELECT GDP FROM Life_Expectancy WHERE Country = 'France' AND Year = 2005;",
        "Analysis": "France's GDP in 2005 was $34,879.73."
    },
    {
        "Question": "What is the average life expectancy in Sweden?",
        "SQL":"SELECT AVG(Life_expectancy) FROM Life_Expectancy WHERE Country = 'Sweden';",
        "Analysis": "The average life expectancy in is 82.51875 Sweden."
    },
    {
        "Question": "Which country had the highest alcohol consumption in 2007?",
        "SQL":"SELECT Country FROM Life_Expectancy WHERE Year = 2007 ORDER BY Alcohol DESC LIMIT 1;",
        "Analysis": "In 2007, Estonia had the highest alcohol consumption."
    },
    {
        "Question": "What was the difference in average life expectancy between Japan and Chad?",
        "SQL":
            """SELECT 
                (SELECT AVG(Life_expectancy) FROM Life_Expectancy WHERE Country = 'Japan') - 
                (SELECT AVG(Life_expectancy) FROM Life_Expectancy WHERE Country = 'Chad') AS Life_Expectancy_Difference;"""
        ,
        "Analysis": "The life expectancy difference between Japan and Chad in 2012 was 31.5 years."
    },
    {
        "Question": "What was the population of Zimbabwe in the year 2000?",
        "SQL": "SELECT Population FROM Life_Expectancy WHERE Country = 'Zimbabwe' AND Year = 2000;",
        "Analysis": "Zimbabwe’s population in 2000 was approximately 12.22 million."
    },
    {
        "Question": "Which country had the highest percentage of expenditure on health in 2015 and what was it?",
        "SQL": "SELECT Country, percentage_expenditure FROM Life_Expectancy WHERE Year = 2015 ORDER BY percentage_expenditure DESC LIMIT 1;",
        "Analysis": "In 2015, Albania had the highest percentage expenditure on health, at 364.9752287%"
    },
    {
        "Question": "What was the BMI in Togo in 2008?",
        "SQL": "SELECT BMI FROM Life_Expectancy WHERE Country = 'Togo' AND Year = 2008;",
        "Analysis": "The BMI of adults in Togo in 2008 was exceptionally low at 2.4."
    },
    {
        "Question": "Which country had the maximum improvement in life expectancy between the years 2000 and 2015?",
        "SQL": 
            """SELECT Country, MAX(Life_Expectancy_Change) AS Max_Improvement 
               FROM (SELECT Country, MAX(Life_expectancy) - MIN(Life_expectancy) AS Life_Expectancy_Change 
                     FROM Life_Expectancy 
                     WHERE Year BETWEEN 2000 AND 2015 
                     GROUP BY Country);"""
        ,
        "Analysis": "Haiti showed the greatest improvement in life expectancy between 2000 and 2015."
    },
    {
        "Question": "What is the mean of infant deaths in South Sudan in the dataset?",
        "SQL": "SELECT AVG(infant_deaths) FROM Life_Expectancy WHERE Country = 'South Sudan';",
        "Analysis": "The mean number of infant deaths per 1000 in South Sudan across all years in the dataset was 27.75."
    },
    {
        "Question": "Which are the unique countries where status is developed?",
        "SQL": """
                        SELECT DISTINCT(Country)
                        FROM Life_Expectancy WHERE Status == 'Developed'
                        ;""",
        "Analysis": "The unique countries are Australia, Austria, Belgium, Bulgaria, Croatia, Cyprus, Czechia, Denmark, Germany, Hungary, Iceland, Ireland, Italy, Japan, Latvia, Lithuania, Luxembourg, Malta, Netherlands, New Zealand, Norway, Poland, Portugal, Romania, Singapore, Slovakia, Slovenia, Spain, Sweden, Switzerland, United Kingdom of Great Britain and Northern Ireland, United States of America."
    }]

In [20]:
# output

conn = sqlite3.connect("database_life_exp.db")
cursor = conn.cursor() # open database


for entry in Questions:
    entry['CorrectData'] = cursor.execute(entry['SQL']).fetchall()
    print(f"Question: {entry['Question']}")
    print(f"Correct Data: {entry['CorrectData']}")
    print(f"Analysis: {entry['Analysis']}")

conn.close()

Question: What was the Gross Domestic Product in France in the year 2005?
Correct Data: [(34879.72633,)]
Analysis: France's GDP in 2005 was $34,879.73.
Question: What is the average life expectancy in Sweden?
Correct Data: [(82.51875,)]
Analysis: The average life expectancy in is 82.51875 Sweden.
Question: Which country had the highest alcohol consumption in 2007?
Correct Data: [('Estonia',)]
Analysis: In 2007, Estonia had the highest alcohol consumption.
Question: What was the difference in average life expectancy between Japan and Chad?
Correct Data: [(32.14999999999999,)]
Analysis: The life expectancy difference between Japan and Chad in 2012 was 31.5 years.
Question: What was the population of Zimbabwe in the year 2000?
Correct Data: [(12222251.0,)]
Analysis: Zimbabwe’s population in 2000 was approximately 12.22 million.
Question: Which country had the highest percentage of expenditure on health in 2015 and what was it?
Correct Data: [('Albania', 364.9752287)]
Analysis: In 2015, Albania had the highest percentage expenditure on health, at 364.9752287%
Question: What was the BMI in Togo in 2008?
Correct Data: [(2.4,)]
Analysis: The BMI of adults in Togo in 2008 was exceptionally low at 2.4.
Question: Which country had the maximum improvement in life expectancy between the years 2000 and 2015?
Correct Data: [('Haiti', 28.700000000000003)]
Analysis: Haiti showed the greatest improvement in life expectancy between 2000 and 2015.
Question: What is the mean of infant deaths in South Sudan in the dataset?
Correct Data: [(27.75,)]
Analysis: The mean number of infant deaths per 1000 in South Sudan across all years in the dataset was 27.75.
Question: Which are the unique countries where status is developed?
Correct Data: [('Australia',), ('Austria',), ('Belgium',), ('Bulgaria',), ('Croatia',), ('Cyprus',), ('Czechia',), ('Denmark',), ('Germany',), ('Hungary',), ('Iceland',), ('Ireland',), ('Italy',), ('Japan',), ('Latvia',), ('Lithuania',), ('Luxembourg',), ('Malta',), ('Netherlands',), ('New Zealand',), ('Norway',), ('Poland',), ('Portugal',), ('Romania',), ('Singapore',), ('Slovakia',), ('Slovenia',), ('Spain',), ('Sweden',), ('Switzerland',), ('United Kingdom of Great Britain and Northern Ireland',), ('United States of America',)]
Analysis: The unique countries are Australia, Austria, Belgium, Bulgaria, Croatia, Cyprus, Czechia, Denmark, Germany, Hungary, Iceland, Ireland, Italy, Japan, Latvia, Lithuania, Luxembourg, Malta, Netherlands, New Zealand, Norway, Poland, Portugal, Romania, Singapore, Slovakia, Slovenia, Spain, Sweden, Switzerland, United Kingdom of Great Britain and Northern Ireland, United States of America.

In [21]:
Questions = pd.DataFrame(Questions)

sql_list = []
dat_list = []
# testing out questions, 
for row in Questions.itertuples(index=False):
    query_res= inference(row.Question, scheme)
    print(query_res)
    SQLcode,gen_answr = extract_data(query_res)
    sql_list.append(SQLcode)
    dat_list.append(gen_answr)

SELECT GDP FROM Life_expectancy WHERE Country = "France" AND YEAR = 2005
SELECT avg(Life_expectancy) FROM Life_expectancy WHERE Country = "Sweden"
SELECT Country FROM Life_expectancy WHERE YEAR = 2007 ORDER BY Alcohol DESC LIMIT 1
SELECT avg(Life_expectancy) FROM Life_expectancy WHERE Country = "Japan" INTERSECT SELECT avg(Life_expectancy) FROM Life_expectancy WHERE Country = "Chad"
SELECT Population FROM Life_expectancy WHERE Country = "Zimbabwe" AND YEAR = 2000
SELECT Country, Total_expenditure FROM Life_expectancy WHERE YEAR = 2015 ORDER BY Total_expenditure DESC LIMIT 1
SELECT BMI FROM LIFE_expectancy WHERE YEAR = 2008 AND country = "Togo"
SELECT Country FROM Life_expectancy WHERE YEAR >= 2000 AND YEAR < = 2015 GROUP BY Country ORDER BY max(Life_expectancy) DESC LIMIT 1
Error: near "=": syntax error
SELECT avg(infant_deaths) FROM Life_expectancy WHERE Country = "South Sudan"
SELECT DISTINCT Country FROM Life_expectancy WHERE Status = "Developed"

In [22]:
# checking if it matches the correct data, and checking the SQL query if not
incorrect_retriever = 0
for i in range(10):
    print(Questions.iloc()[i]['Question'])
    print(Questions.iloc()[i]['CorrectData'])
    print(dat_list[i])

    if dat_list[i] != Questions.iloc()[i]['CorrectData']:
        print(sql_list[i])
        incorrect_retriever += 1

What was the Gross Domestic Product in France in the year 2005?
[(34879.72633,)]
[(34879.72633,)]
What is the average life expectancy in Sweden?
[(82.51875,)]
[(82.51875,)]
Which country had the highest alcohol consumption in 2007?
[('Estonia',)]
[('Estonia',)]
What was the difference in average life expectancy between Japan and Chad?
[(32.14999999999999,)]
[]
SELECT avg(Life_expectancy) FROM Life_expectancy WHERE Country = "Japan" INTERSECT SELECT avg(Life_expectancy) FROM Life_expectancy WHERE Country = "Chad"
What was the population of Zimbabwe in the year 2000?
[(12222251.0,)]
[(12222251.0,)]
Which country had the highest percentage of expenditure on health in 2015 and what was it?
[('Albania', 364.9752287)]
[('Afghanistan', 8.16)]
SELECT Country, Total_expenditure FROM Life_expectancy WHERE YEAR = 2015 ORDER BY Total_expenditure DESC LIMIT 1
What was the BMI in Togo in 2008?
[(2.4,)]
[(2.4,)]
Which country had the maximum improvement in life expectancy between the years 2000 and 2015?
[('Haiti', 28.700000000000003)]
The SQL query didnt go through
SELECT Country FROM Life_expectancy WHERE YEAR >= 2000 AND YEAR < = 2015 GROUP BY Country ORDER BY max(Life_expectancy) DESC LIMIT 1
What is the mean of infant deaths in South Sudan in the dataset?
[(27.75,)]
[(27.75,)]
Which are the unique countries where status is developed?
[('Australia',), ('Austria',), ('Belgium',), ('Bulgaria',), ('Croatia',), ('Cyprus',), ('Czechia',), ('Denmark',), ('Germany',), ('Hungary',), ('Iceland',), ('Ireland',), ('Italy',), ('Japan',), ('Latvia',), ('Lithuania',), ('Luxembourg',), ('Malta',), ('Netherlands',), ('New Zealand',), ('Norway',), ('Poland',), ('Portugal',), ('Romania',), ('Singapore',), ('Slovakia',), ('Slovenia',), ('Spain',), ('Sweden',), ('Switzerland',), ('United Kingdom of Great Britain and Northern Ireland',), ('United States of America',)]
[('Australia',), ('Austria',), ('Belgium',), ('Bulgaria',), ('Croatia',), ('Cyprus',), ('Czechia',), ('Denmark',), ('Germany',), ('Hungary',), ('Iceland',), ('Ireland',), ('Italy',), ('Japan',), ('Latvia',), ('Lithuania',), ('Luxembourg',), ('Malta',), ('Netherlands',), ('New Zealand',), ('Norway',), ('Poland',), ('Portugal',), ('Romania',), ('Singapore',), ('Slovakia',), ('Slovenia',), ('Spain',), ('Sweden',), ('Switzerland',), ('United Kingdom of Great Britain and Northern Ireland',), ('United States of America',)]

In [23]:
accuracy_base= 1-(incorrect_retriever/10)
accuracy_base

0.7

In [24]:

def preprocess_function(example):
    """
    Preprocess dataset for T5 fine-tuning.
    
    Args:
        example: A question.
        
    Returns:
        dict: Processed inputs and targets suitable for the T5 model.
    """

    
    # Extract relevant fields
    question = example["question"].strip()
      
    query = example["answer"].strip()
        
    # Combine question and database identifier into a single input
    input_str = f"convert question and table into SQL query. Question: {question} | Table: Life_Expectancy"
        
    
    # Tokenize the input and target sequences
    model_inputs = tokenizer(input_str, text_target=query, max_length=1000, truncation=True)
    return model_inputs

In [25]:
aggregate_questions = {'train':[
    {"question": "Which country had the maximum life expectancy?",
     "answer": "SELECT Country FROM Life_Expectancy ORDER BY Life_expectancy DESC LIMIT 1;"},
    {"question": "What is the difference in average life expectancy between France and Germany?",
    "answer": """SELECT 
                         (SELECT AVG(Life_expectancy) FROM Life_Expectancy WHERE Country = 'France') - 
                         (SELECT AVG(Life_expectancy) FROM Life_Expectancy WHERE Country = 'Germany') AS Life_Expectancy_Difference;"""},
    {"question": "What is the average life expectancy for the top 5 countries with the highest GDP in 2010?",
    "answer": """SELECT AVG(Life_expectancy) 
                     FROM (SELECT Country, AVG(Life_expectancy) AS Life_expectancy
                           FROM Life_Expectancy 
                           WHERE Year = 2010 
                           ORDER BY GDP DESC 
                           LIMIT 5) AS Top5Countries;"""},
    {"question": "Which country had the largest percentage increase in life expectancy from 2000 to 2015?",
    "answer": """SELECT Country, 
                            ((MAX(Life_expectancy) - MIN(Life_expectancy)) / MIN(Life_expectancy)) * 100 AS Percentage_Change
                     FROM Life_Expectancy
                     WHERE Year BETWEEN 2000 AND 2015
                     GROUP BY Country
                     ORDER BY Percentage_Change DESC
                     LIMIT 1;"""},
    {"question": "Which year had the greatest disparity in life expectancy between countries?",
    "answer": """SELECT Year, MAX(Life_expectancy) - MIN(Life_expectancy) AS Disparity
                     FROM Life_Expectancy
                     GROUP BY Year
                     ORDER BY Disparity DESC
                     LIMIT 1;"""},
    {"question": "Which country had the highest average alcohol consumption between 2000 and 2015?",
    "answer": """SELECT Country, AVG(Alcohol) AS Avg_Alcohol
                     FROM Life_Expectancy
                     WHERE Year BETWEEN 2000 AND 2015
                     GROUP BY Country
                     ORDER BY Avg_Alcohol DESC
                     LIMIT 1;"""},
    {"question": "What is the correlation between percentage expenditure on health and life expectancy for developed countries?",
    "answer": """SELECT CORR(percentage_expenditure, Life_expectancy) AS Correlation
                     FROM Life_Expectancy
                     WHERE Status = 'Developed';"""},
    {"question": "What is the total number of under-five deaths in developing countries in 2010?",
        "answer": """SELECT SUM(under_five_deaths) AS Total_Under_Five_Deaths
                     FROM Life_Expectancy
                     WHERE Status = 'Developing' AND Year = 2010;"""},
     {"question": "Which country had the highest BMI in 2015 and what was it?",
        "answer": """SELECT Country, MAX(BMI) AS max_bmi
                     FROM Life_Expectancy
                     WHERE Year = 2015;"""},
    {"question": "Which year had the highest number of infant deaths and what was it?",
     "answer": "SELECT Year, SUM(infant_deaths) AS Total_Infant_Deaths FROM Life_Expectancy GROUP BY Year ORDER BY Total_Infant_Deaths DESC LIMIT 1;"},
    {"question": "Which country had the maximum life expectancy increase between 2000 and 2010?",
    "answer": "SELECT Country FROM (SELECT Country, MAX(Life_expectancy) - MIN(Life_expectancy) AS Life_Expectancy_Change FROM Life_Expectancy WHERE Year BETWEEN 2000 AND 2010 GROUP BY Country) ORDER BY Life_Expectancy_Change DESC LIMIT 1;"},
    {"question": "Which country spent the highest percentage of expenditure on health?",
     "answer": "SELECT Country FROM Life_Expectancy WHERE percentage_expenditure = (SELECT MAX(percentage_expenditure) FROM Life_Expectancy);"},
    {"question": "Which country had the highest GDP per capita in 2005 and what was the value?",
    "answer": """SELECT Country, MAX(GDP) AS Highest_GDP
                     FROM Life_Expectancy
                     WHERE Year = 2005;"""},
    {"question": "Which country had the most cases of measles in 2005?",
     "answer": "SELECT Country FROM Life_Expectancy WHERE Year = 2005 AND Measles = (SELECT MAX(Measles) FROM Life_Expectancy WHERE Year = 2005);"},
    {"question": "Which country had the highest number of under-five deaths in 2010?",
     "answer": "SELECT Country FROM Life_Expectancy WHERE Year = 2010 AND under_five_deaths = (SELECT MAX(under_five_deaths) FROM Life_Expectancy WHERE Year = 2010);"},
    {"question": "Which year had the highest total expenditure on health?",
     "answer": "SELECT Year FROM Life_Expectancy WHERE Total_expenditure = (SELECT MAX(Total_expenditure) FROM Life_Expectancy);"},
    {"question": "Which country had the highest HIV/AIDS mortality rate?",
     "answer": "SELECT Country FROM Life_Expectancy WHERE HIV_AIDS = (SELECT MAX(HIV_AIDS) FROM Life_Expectancy);"},
    { "question": "Which year had the maximum number of under-five deaths globally?",
    "answer": "SELECT Year FROM Life_Expectancy WHERE under_five_deaths = (SELECT MAX(under_five_deaths) FROM Life_Expectancy);"},
    {"question": "Which country had the largest population in the dataset?",
     "answer": "SELECT Country FROM Life_Expectancy WHERE Population = (SELECT MAX(Population) FROM Life_Expectancy);"},
    {"question": "What is the mean thinness percentage for children aged 1 to 19 years?",
     "answer": "SELECT AVG(thinness_1_19_years) FROM Life_Expectancy;"},
    {"question": "Which country had the lowest income composition of resources?",
     "answer": "SELECT Country FROM Life_Expectancy WHERE Income_composition_of_resources = (SELECT MIN(Income_composition_of_resources) FROM Life_Expectancy);"},
    {"question": "What is the global average for under_five deaths?", 
     "answer": "SELECT AVG(under_five_deaths) FROM Life_Expectancy;"},
    {"question": "Which country had the lowest GDP in 2005?",
    "answer": "SELECT Country FROM Life_Expectancy WHERE Year = 2005 ORDER BY GDP ASC LIMIT 1;"},
    {"question": "What is the difference in total health expenditure as a percentage of GDP between the United States and the United Kingdom in 2010?",
        "answer": """SELECT 
                         (SELECT Total_expenditure 
                          FROM Life_Expectancy WHERE Country = 'United States' AND Year = 2010) - 
                         (SELECT Total_expenditure 
                          FROM Life_Expectancy WHERE Country = 'United Kingdom' AND Year = 2010) AS Expenditure_Difference;"""},
    {"question": "Which year had the highest alcohol consumption globally?", 
     "answer": "SELECT Year FROM Life_Expectancy WHERE Alcohol = (SELECT MAX(Alcohol) FROM Life_Expectancy);"},
    {"question": "Which country had the lowest diphtheria immunization rate in 2015?",
     "answer": "SELECT Country FROM Life_Expectancy WHERE Year = 2015 AND Diphtheria = (SELECT MIN(Diphtheria) FROM Life_Expectancy WHERE Year = 2015);"},
    {"question": "What is the average schooling years for developing countries?",
     "answer": "SELECT AVG(Schooling) FROM Life_Expectancy WHERE Status = 'Developing';"},
    {"question": "Which country had the maximum improvement in life expectancy between 2000 and 2015?", "answer": "SELECT Country, (MAX(Life_expectancy) - MIN(Life_expectancy)) AS Improvement FROM Life_Expectancy WHERE Year BETWEEN 2000 AND 2015 GROUP BY Country ORDER BY Improvement DESC LIMIT 1;"},
    {"question": "Which year had the lowest average life expectancy?",
     "answer": "SELECT Year FROM Life_Expectancy GROUP BY Year ORDER BY AVG(Life_expectancy) ASC LIMIT 1;"},
    {"question": "Which country had the most significant improvement in BMI between 2000 and 2015?",
     "answer": "SELECT Country, (MAX(BMI) - MIN(BMI)) AS Improvement FROM Life_Expectancy WHERE Year BETWEEN 2000 AND 2015 GROUP BY Country ORDER BY Improvement DESC LIMIT 1;"},
    {"question": "Which country had the most infant deaths in 2010?",
     "answer": "SELECT Country FROM Life_Expectancy WHERE Year = 2010 AND infant_deaths = (SELECT MAX(infant_deaths) FROM Life_Expectancy WHERE Year = 2010);"},
    {"question": "Which country had the highest percentage expenditure in 2007?",
     "answer": "SELECT Country FROM Life_Expectancy WHERE Year = 2007 AND percentage_expenditure = (SELECT MAX(percentage_expenditure) FROM Life_Expectancy WHERE Year = 2007);"},
    {"question": "What is the global average income composition of resources?",
     "answer": "SELECT AVG(Income_composition_of_resources) FROM Life_Expectancy;"},
    {"question": "Which year had the highest global adult mortality rate?", 
     "answer": "SELECT Year FROM Life_Expectancy WHERE Adult_Mortality = (SELECT MAX(Adult_Mortality) FROM Life_Expectancy);"},
    {"question": "Which country had a greater improvement in life expectancy between 2000 and 2015: Japan or South Korea?",
    "answer": """SELECT 
                         CASE 
                             WHEN (SELECT MAX(Life_expectancy) - MIN(Life_expectancy) 
                                   FROM Life_Expectancy WHERE Country = 'Japan' AND Year BETWEEN 2000 AND 2015) > 
                                  (SELECT MAX(Life_expectancy) - MIN(Life_expectancy) 
                                   FROM Life_Expectancy WHERE Country = 'South Korea' AND Year BETWEEN 2000 AND 2015) 
                             THEN 'Japan' 
                             ELSE 'South Korea' 
                         END AS Greater_Improvement;"""},
    {"question": "Which country had the maximum schooling years in 2010?",
     "answer": "SELECT Country FROM Life_Expectancy WHERE Year = 2010 AND Schooling = (SELECT MAX(Schooling) FROM Life_Expectancy WHERE Year = 2010);"},
    {"question": "Which year had the lowest average Gross Domestic Product?", 
     "answer": "SELECT Year FROM Life_Expectancy GROUP BY Year ORDER BY AVG(GDP) ASC LIMIT 1;"},
    {"question": "Which country had the lowest Gross Domestic Product in 2005?",
     "answer": "SELECT Country FROM Life_Expectancy WHERE Year = 2005 AND GDP = (SELECT MIN(GDP) FROM Life_Expectancy WHERE Year = 2005);"},
    {"question": "Which country had the lowest BMI in 2015 and what was it?",
     "answer": "SELECT Country, MIN(BMI) FROM Life_Expectancy WHERE Year = 2015 AND BMI = (SELECT MIN(BMI) FROM Life_Expectancy WHERE Year = 2015);"},
    {"question": "Which year had the maximum improvement in life expectancy globally?",
     "answer": "SELECT Year, (MAX(Life_expectancy) - MIN(Life_expectancy)) AS Improvement FROM Life_Expectancy GROUP BY Year ORDER BY Improvement DESC LIMIT 1;"},
    {"question": "Which country had the highest diphtheria immunization rate in 2008?",
     "answer": "SELECT Country FROM Life_Expectancy WHERE Year = 2008 AND Diphtheria = (SELECT MAX(Diphtheria) FROM Life_Expectancy WHERE Year = 2008);"},
    {"question": "What is the difference in life expectancy between Sweden and USA?",
     "answer": """SELECT 
                     (SELECT Life_expectancy FROM Life_Expectancy WHERE Country = 'Sweden') - 
                     (SELECT Life_expectancy FROM Life_Expectancy WHERE Country = 'USA') AS Difference;"""},
    {"question": "What is the difference in average Gross Domestic Product between Uganda and Nigeria?",
     "answer": """SELECT 
                     (SELECT AVG(GDP) FROM Life_Expectancy WHERE Country = 'Uganda') - 
                     (SELECT AVG(GDP) FROM Life_Expectancy WHERE Country = 'Nigeria') AS GDP_Difference;"""},
    {"question": "What is the difference in average Gross Domestic Product between Spain and Japan?",
     "answer": """SELECT 
                     (SELECT AVG(GDP) FROM Life_Expectancy WHERE Country = 'Spain') - 
                     (SELECT AVG(GDP) FROM Life_Expectancy WHERE Country = 'Japan') AS GDP_Difference;"""},
    {"question": "Which country showed the largest percentage improvement in immunization (Hepatitis B) between 2005 and 2015?",
        "answer": """SELECT Country, 
                            MAX(Hepatitis_B) - MIN(Hepatitis_B) AS Improvement
                     FROM Life_Expectancy 
                     WHERE Year IN (2005, 2015) 
                     GROUP BY Country 
                     ORDER BY Improvement DESC 
                     LIMIT 1;"""},
    {"question": "What is the average BMI of countries with a population greater than 50 million?",
        "answer": """SELECT AVG(BMI) AS Avg_BMI
                     FROM Life_Expectancy
                     WHERE Population > 50000000;"""},
    {"question": "Which country had the maximum difference in schooling years between 2000 and 2015?",
        "answer": """SELECT Country, 
                            MAX(Schooling) - MIN(Schooling) AS Schooling_Difference
                     FROM Life_Expectancy
                     WHERE Year BETWEEN 2000 AND 2015
                     GROUP BY Country
                     ORDER BY Schooling_Difference DESC
                     LIMIT 1;"""},
    {"question": "What is the correlation between GDP and life expectancy across all years?",
        "answer": """SELECT CORR(GDP, Life_expectancy) AS GDP_LifeExpectancy_Correlation
                     FROM Life_Expectancy;""" },
    {"question": "Which countries had a higher average life expectancy than the global average in 2012?",
        "answer": """SELECT Country 
                     FROM Life_Expectancy 
                     WHERE Year = 2012 
                     AND Life_expectancy > (SELECT AVG(Life_expectancy) FROM Life_Expectancy WHERE Year = 2012);"""},
    {"question": "Which country had the highest alcohol consumption in 2015 and what was it?",
        "answer": """SELECT Country, MAX(Alcohol) AS Highest_Alcohol_Consumption
                     FROM Life_Expectancy 
                     WHERE Year = 2015
                     GROUP BY Country
                     ORDER BY Highest_Alcohol_Consumption DESC
                     LIMIT 1;"""},
    {"question": "What is the average percentage expenditure on health for developed countries compared to developing countries?",
    "answer": """SELECT 
                         (SELECT AVG(percentage_expenditure) 
                          FROM Life_Expectancy 
                          WHERE Status = 'Developed') AS Avg_Developed_Expenditure,
                         (SELECT AVG(percentage_expenditure) 
                          FROM Life_Expectancy 
                          WHERE Status = 'Developing') AS Avg_Developing_Expenditure;""" },
    {"question": "Which country had the highest GDP per capita in 2015 and what was the value?",
    "answer": """SELECT Country, MAX(GDP) AS Highest_GDP
                     FROM Life_Expectancy 
                     WHERE Year = 2015 
                     GROUP BY Country 
                     ORDER BY Highest_GDP DESC 
                     LIMIT 1;"""},
    {
    "question": "Which country had a higher percentage expenditure on health in 2010: the United States or Canada?",
    "answer": """SELECT 
                     CASE 
                         WHEN (SELECT percentage_expenditure FROM Life_Expectancy WHERE Country = 'United States' AND Year = 2010) > 
                              (SELECT percentage_expenditure FROM Life_Expectancy WHERE Country = 'Canada' AND Year = 2010) 
                         THEN 'United States' 
                         ELSE 'Canada' 
                     END AS Higher_Percentage_Expenditure;"""}],    

                       
    'validation':[   {
    "question": "What was the average schooling in developed countries in 2010?",
    "answer": "SELECT AVG(Schooling) FROM Life_Expectancy WHERE Status = 'Developed' AND Year = 2010;"},
    {"question": "What is the difference in average GDP per capita between Norway and Sweden?",
    "answer": """SELECT 
                         (SELECT AVG(GDP) FROM Life_Expectancy WHERE Country = 'Norway') - 
                         (SELECT AVG(GDP) FROM Life_Expectancy WHERE Country = 'Sweden') AS GDP_Difference;"""},
    {"question": "Which country had the highest HIV/AIDS prevalence in 2008?",
    "answer": "SELECT Country FROM Life_Expectancy WHERE Year = 2008 ORDER BY HIV_AIDS DESC LIMIT 1;"},
    {"question": "Which country had the greatest decline in BMI between 2000 and 2015?",
    "answer": """SELECT Country, MIN(BMI) - MAX(BMI) AS Decline
                     FROM Life_Expectancy
                     WHERE Year BETWEEN 2000 AND 2015
                     GROUP BY Country
                     ORDER BY Decline ASC
                     LIMIT 1;"""},
    {"question": "Which country had the lowest Thinnes of 5 to 9 years old in 2010 and what was it?",
    "answer": """SELECT Country, MIN(thinness_5_9_years) AS Lowest_thinness
                     FROM Life_Expectancy
                     WHERE Year = 2010;"""},
    {"question": "Which country had the highest total expenditure in 2013?", 
     "answer": "SELECT Country FROM Life_Expectancy WHERE Year = 2013 AND Total_expenditure = (SELECT MAX(Total_expenditure) FROM Life_Expectancy WHERE Year = 2013);"},
    {"question": "What is the difference in average Gross Domestic Product between Germany and Nigeria?",
     "answer": """SELECT 
                     (SELECT AVG(GDP) FROM Life_Expectancy WHERE Country = 'Germany') - 
                     (SELECT AVG(GDP) FROM Life_Expectancy WHERE Country = 'Nigeria') AS GDP_Difference;"""},
    {"question": "What is the difference in mean BMI between developing and developed countries?",
    "answer": "SELECT (SELECT AVG(BMI) FROM Life_Expectancy WHERE Status = 'Developing') - (SELECT AVG(BMI) FROM Life_Expectancy WHERE Status = 'Developed') AS BMI_Difference;"},
    {"question": "Which country had the lowest infant mortality rate in 2008, and what was the rate?",
    "answer": """SELECT Country, MIN(infant_deaths) AS Lowest_Infant_Mortality
                     FROM Life_Expectancy 
                     WHERE Year = 2008 
                     GROUP BY Country 
                     ORDER BY Lowest_Infant_Mortality ASC 
                     LIMIT 1;"""},
    {"question": "What is the total population of all developed countries in the dataset?",
    "answer": """SELECT SUM(Population) AS Total_Developed_Population 
                     FROM Life_Expectancy 
                     WHERE Status = 'Developed';"""},
    {"question": "What was the population in UK in the year 2001?",
    "answer":"SELECT Population FROM Life_Expectancy WHERE Country = 'United Kingdom' AND Year = 2001;"},
    {"question": "What is the difference in average Gross Domestic Product between South Korea and Viet nam?",
    "answer": """SELECT 
                     (SELECT AVG(GDP) FROM Life_Expectancy WHERE Country = 'South Korea') - 
                     (SELECT AVG(GDP) FROM Life_Expectancy WHERE Country = 'Viet nam') AS GDP_Difference;"""}
]}

In [26]:
# preprocess
train_dataset = [preprocess_function(item) for item in aggregate_questions["train"]]
val_dataset = [preprocess_function(item) for item in aggregate_questions["validation"]]

In [27]:
print(len(train_dataset))
print(len(val_dataset))

53
12

In [28]:
# declare model
model_tune = model
model_tune  = model_tune.cuda()

In [29]:
# collator to for padding during batching
from transformers import DataCollatorForSeq2Seq
from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model_tune)

In [30]:

import os
os.environ["TOKENIZERS_PARALLELISM"] = "true"  # Enable tokenizer parallelism
# Disable W&B logging
os.environ["WANDB_DISABLED"] = "true"
# In your training arguments
training_args = Seq2SeqTrainingArguments(
    output_dir="./results",
    eval_strategy="steps",
    eval_steps=1,
    learning_rate=1e-5,
    per_device_train_batch_size=5,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=2,
    warmup_ratio=0.01,
    weight_decay=0.1,
    save_total_limit=1,
    num_train_epochs=4,
    fp16=True,
    predict_with_generate=True,
    lr_scheduler_type="cosine",
    dataloader_num_workers=4,  # Increase the number of workers for parallelism
    greater_is_better=False,
    metric_for_best_model="eval_loss" ,
    load_best_model_at_end=True  # This will load the best model at the end of training

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [31]:
#  trainer
trainer = Seq2SeqTrainer(
    model=model_tune,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    processing_class=tokenizer,
    data_collator=data_collator
)

In [32]:
trainer.train()

/opt/conda/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.48.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.
/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '

/opt/conda/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight'].

TrainOutput(global_step=12, training_loss=1.762264092763265, metrics={'train_runtime': 23.4505, 'train_samples_per_second': 9.04, 'train_steps_per_second': 0.512, 'total_flos': 11607697059840.0, 'train_loss': 1.762264092763265, 'epoch': 4.0})

In [33]:
# Save the trained model
model_tune.save_pretrained("/kaggle/working/trained_model")

In [34]:
def inference_tune(question: str, tables: dict[str, List[str]]) -> str:
    input_data = prepare_input(question=question, tables=tables)
    input_data = input_data.to(model_tune.device)
    outputs = model_tune.generate(inputs=input_data,  max_length=1000)
    result = tokenizer.decode(token_ids=outputs[0], skip_special_tokens=True)
    return result

In [35]:

sql_tune = []
dat_tune = []
# testing out questions, 
for row in Questions.itertuples(index=False):
    query_res= inference_tune(row.Question, scheme)
    print(query_res)
    SQLcode,gen_answr = extract_data(query_res)
    sql_tune.append(SQLcode)
    dat_tune.append(gen_answr)

SELECT GDP FROM Life_expectancy WHERE Country = "France" AND YEAR = 2005
SELECT avg(Life_expectancy) FROM Life_expectancy WHERE Country = "Sweden"
SELECT Country FROM Life_expectancy WHERE YEAR = 2007 ORDER BY Alcohol DESC LIMIT 1
SELECT avg(Life_expectancy) FROM Life_expectancy WHERE Country = "Japan" INTERSECT SELECT avg(Life_expectancy) FROM Life_expectancy WHERE Country = "Chad"
SELECT Population FROM Life_expectancy WHERE Country = "Zimbabwe" AND YEAR = 2000
SELECT Country, Total_expenditure FROM Life_expectancy WHERE YEAR = 2015 ORDER BY Total_expenditure DESC LIMIT 1
SELECT BMI FROM Life_expectancy WHERE Country = "Togo" AND YEAR = 2008
SELECT Country FROM Life_expectancy WHERE YEAR BETWEEN 2000 AND 2015 ORDER BY Life_expectancy DESC LIMIT 1
SELECT avg(infant_deaths) FROM Life_expectancy WHERE Country = "South Sudan"
SELECT DISTINCT Country FROM Life_expectancy WHERE Status = "Developed"

In [36]:
# checking if it matches the correct data, and checking the SQL query if not
incorrect_retriever_tune = 0
for i in range(10):
    print(Questions.iloc()[i]['Question'])
    print(Questions.iloc()[i]['CorrectData'])
    print(dat_tune[i])

    if dat_tune[i] != Questions.iloc()[i]['CorrectData']:
        print(sql_tune[i])
        incorrect_retriever_tune += 1

What was the Gross Domestic Product in France in the year 2005?
[(34879.72633,)]
[(34879.72633,)]
What is the average life expectancy in Sweden?
[(82.51875,)]
[(82.51875,)]
Which country had the highest alcohol consumption in 2007?
[('Estonia',)]
[('Estonia',)]
What was the difference in average life expectancy between Japan and Chad?
[(32.14999999999999,)]
[]
SELECT avg(Life_expectancy) FROM Life_expectancy WHERE Country = "Japan" INTERSECT SELECT avg(Life_expectancy) FROM Life_expectancy WHERE Country = "Chad"
What was the population of Zimbabwe in the year 2000?
[(12222251.0,)]
[(12222251.0,)]
Which country had the highest percentage of expenditure on health in 2015 and what was it?
[('Albania', 364.9752287)]
[('Afghanistan', 8.16)]
SELECT Country, Total_expenditure FROM Life_expectancy WHERE YEAR = 2015 ORDER BY Total_expenditure DESC LIMIT 1
What was the BMI in Togo in 2008?
[(2.4,)]
[(2.4,)]
Which country had the maximum improvement in life expectancy between the years 2000 and 2015?
[('Haiti', 28.700000000000003)]
[('Belgium',)]
SELECT Country FROM Life_expectancy WHERE YEAR BETWEEN 2000 AND 2015 ORDER BY Life_expectancy DESC LIMIT 1
What is the mean of infant deaths in South Sudan in the dataset?
[(27.75,)]
[(27.75,)]
Which are the unique countries where status is developed?
[('Australia',), ('Austria',), ('Belgium',), ('Bulgaria',), ('Croatia',), ('Cyprus',), ('Czechia',), ('Denmark',), ('Germany',), ('Hungary',), ('Iceland',), ('Ireland',), ('Italy',), ('Japan',), ('Latvia',), ('Lithuania',), ('Luxembourg',), ('Malta',), ('Netherlands',), ('New Zealand',), ('Norway',), ('Poland',), ('Portugal',), ('Romania',), ('Singapore',), ('Slovakia',), ('Slovenia',), ('Spain',), ('Sweden',), ('Switzerland',), ('United Kingdom of Great Britain and Northern Ireland',), ('United States of America',)]
[('Australia',), ('Austria',), ('Belgium',), ('Bulgaria',), ('Croatia',), ('Cyprus',), ('Czechia',), ('Denmark',), ('Germany',), ('Hungary',), ('Iceland',), ('Ireland',), ('Italy',), ('Japan',), ('Latvia',), ('Lithuania',), ('Luxembourg',), ('Malta',), ('Netherlands',), ('New Zealand',), ('Norway',), ('Poland',), ('Portugal',), ('Romania',), ('Singapore',), ('Slovakia',), ('Slovenia',), ('Spain',), ('Sweden',), ('Switzerland',), ('United Kingdom of Great Britain and Northern Ireland',), ('United States of America',)]

In [37]:
incorrect_retriever_tune = 1-(incorrect_retriever_tune/10)
incorrect_retriever_tune

0.7

In [56]:
import re

def Exact_M(generated, reference,tokeniser):
    """
    Compute the Exact Match (EM) score as a proportion of matching queries.
    Arguments:
        generated (str): The generated query as a single string.
        reference (str): The reference query as a single string.
        tokeniser: A tokenizer object that processes the strings into tokenized representations.
    Returns:
        float: 1.0 if the queries match exactly after preprocessing, 0.0 otherwise.
    """
    # Preprocess to remove unnecessary symbols
    def preprocess(query):
        # Remove single quotes, double quotes, and other unnecessary symbols
        return re.sub(r"[\"\'\;\s]+", " ", query).strip().lower()
        
    # Apply preprocessing
    generated = preprocess(generated)
    reference = preprocess(reference)

    # Tokenize the generated and reference queries
    generated_doc = tokeniser(generated).input_ids
    reference_doc = tokeniser(reference).input_ids

    # Check for exact match
    EM_score = 1.0 if generated_doc == reference_doc else 0.0
    return EM_score

In [57]:

Exact_M_scores = []
Exact_M_scores_tuned = []

# Loop through each question and compare the generated SQL to the reference SQL
for i in range(len(Questions)):
    generated_sql = sql_list[i]  # Assuming sql_list contains generated SQL statements
    generated_sql_tune = sql_tune[i]  # Assuming sql_list contains generated SQL statements
    reference_sql = Questions.iloc()[i]["SQL"]  # Extract reference SQL from the "SQL" field in Questions

    # Calculate exact match
    Exact_M_score = Exact_M(generated_sql, reference_sql,tokenizer)
    Exact_M_scores.append(Exact_M_score)
    Exact_M_scores_tune = Exact_M(generated_sql_tune, reference_sql,tokenizer)
    Exact_M_scores_tuned.append(Exact_M_scores_tune)

# Now you can compute the average ROUGE-2 score (or other aggregation metrics)
average_Exact_M_scores = sum(Exact_M_scores) / len(Exact_M_scores)

print(f"Proportion of Exact matching score for base model: {average_Exact_M_scores}")

average_Exact_M_scores_tuned = sum(Exact_M_scores_tuned) / len(Exact_M_scores_tuned)

print(f"Proportion of Exact matching score for tuned model: {average_Exact_M_scores_tuned}")

Proportion of Exact matching score for base model: 0.5
Proportion of Exact matching score for tuned model: 0.6

In [58]:
from huggingface_hub  import login

In [59]:
login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [60]:


from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

# Load the Llama-3.2-3B model and tokenizer
model_name = "meta-llama/Llama-3.2-3B"

# Load the model and tokenizer
llm_tokenizer = AutoTokenizer.from_pretrained(model_name)
llm_model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", torch_dtype="auto")

tokenizer_config.json:   0%|          | 0.00/50.5k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/301 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/844 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/20.9k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/1.46G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/185 [00:00<?, ?B/s]

In [61]:

# Define the function for generating responses
def generate_response(user_input,table_desc):
    """
    Generate a response using a structured prompt format with system, analysis, user input.
    """
    # Construct the structured prompt
    prompt = f"""
                System: You are a Generator (Knowledge assistant) in a RAG system tasked with providing a concise and detailed analysis of the data retrieved based on the user's question in 2 sentences. Ensure clarity and focus on the key details. The retriever can make mistakes. 
                       
                Database description:{table_desc}
                
                User input: {user_input}

                Assistant:
                """
    
    # Tokenize the input
    inputs = llm_tokenizer(prompt, return_tensors="pt", truncation=True, max_length=1024).to(llm_model.device)

    # Generate the response
    outputs = llm_model.generate(
        **inputs,
        max_new_tokens=100,
        temperature=0.1, # low randomness in answers
        top_p=0.90,
        pad_token_id=llm_tokenizer.eos_token_id
    )

    # Decode the response
    response = llm_tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Extract the assistant's response (remove the prompt part)
    assistant_response =  response.split("Assistant:")[-1].strip()
    assistant_response = assistant_response.split("\n")[0]
    return assistant_response


def RAG(question,scheme,table_desc):
    """Produce an abtractive summary for a given text.
    Retrive data and generate an answer given a question
    
    """
    query = inference_tune(question, scheme)
    
    sql,data = extract_data(query)


    user_prompt =  f"""" User question: {question} 
                         Retrieved Data: {data}"""
    
    if data == [] or data == 'The SQL query didnt go through':
        return 'The SQL query didnt go through, failed to retrieve any data'
    else:
        response = generate_response(user_prompt,table_desc)
        return response

In [62]:

start_time = time.time()
resp = RAG('What was the population in France in year 2009?',scheme,table_desc)
end_time = time.time()
print("Execution time: ", end_time - start_time,"secs")

Execution time:  6.9522154331207275 secs

In [63]:
resp

'The population of France in 2009 was 647744.0'

In [64]:
from collections import Counter


def rouge_2(generated, reference,tokeniser):
    """Compute the ROUGE-2 score between a system output and a reference.

    Arguments:
        generated (str): The generated output, as a single string.
        reference (str): The reference to compare against, as a single string.

    Returns:
        The F1-score of the ROUGE-2 metric between system output and reference.
    """
    
    generated_doc = tokeniser(generated).input_ids
    reference_doc = tokeniser(reference).input_ids
    # Generate bigrams (pairs of consecutive words)
    generated_bigrams = [(generated_doc[i], generated_doc[i + 1]) for i in range(len(generated_doc) - 1)]
    reference_bigrams = [(reference_doc[i], reference_doc[i + 1]) for i in range(len(reference_doc) - 1)]

    # Count bigrams using Counter
    generated_bigram_set = Counter(generated_bigrams)
    reference_bigram_set = Counter(reference_bigrams)

    # Calculate overlap between system and reference bigrams
    overlap = generated_bigram_set & reference_bigram_set

    # Compute precision, recall, and F1-score
    if len(generated_bigram_set) > 0:
        precision = sum(overlap.values()) / sum(generated_bigram_set.values())
    else:
        precision = 0

    if len(reference_bigram_set) > 0:
        recall = sum(overlap.values()) / sum(reference_bigram_set.values())
    else:
        recall = 0

    # Compute F1-score
    if precision + recall > 0:
        f1_score = (2 * precision * recall) / (precision + recall)
    else:
        f1_score = 0

    return f1_score

In [66]:

abstractive = []
abstractive_rouge_2 = []
correctdata_rouge_2 = []

for i in range(10): # looping over all question
    gen_answer = RAG(Questions.iloc()[i]['Question'], scheme,table_desc) #Running full model
    abstractive.append(gen_answer)
    rouge_scores = rouge_2(gen_answer, entry["Analysis"],llm_tokenizer) # calculate score
    abstractive_rouge_2.append(rouge_scores)
    if dat_tune[i] == Questions.iloc()[i]['CorrectData']: # only the ones with correct data 
        correctdata_rouge_2.append(rouge_2(gen_answer, entry["Analysis"],llm_tokenizer))


print(f'The Average Rouge2 score is:{sum(abstractive_rouge_2)/10}')
print(f'The Average Rouge2 score of correct retrieved data is:{sum(correctdata_rouge_2)/7}')

The Average Rouge2 score is:0.10917499949290974
The Average Rouge2 score of correct retrieved data is:0.14849746823643548

In [67]:

pd.set_option('display.max_colwidth', None)

pd.DataFrame({
    "Question":  Questions.loc[:, "Question"],
    "True analysis": Questions.loc[:, "Analysis"],
    "Generated analysis": abstractive
})

,Question,True analysis,Generated analysis
0,What was the Gross Domestic Product in France in the year 2005?,"France's GDP in 2005 was $34,879.73.",The Gross Domestic Product in France in the year 2005 was 34879.72633 USD.
1,What is the average life expectancy in Sweden?,The average life expectancy in is 82.51875 Sweden.,The average life expectancy in Sweden is 82.51875 years.
2,Which country had the highest alcohol consumption in 2007?,"In 2007, Estonia had the highest alcohol consumption.",The country with the highest alcohol consumption in 2007 was Estonia with 11.6 litres of pure alcohol per capita (15+).
3,What was the difference in average life expectancy between Japan and Chad?,The life expectancy difference between Japan and Chad in 2012 was 31.5 years.,"The SQL query didnt go through, failed to retrieve any data"
4,What was the population of Zimbabwe in the year 2000?,Zimbabwe’s population in 2000 was approximately 12.22 million.,The population of Zimbabwe in the year 2000 was 12222251.0.
5,Which country had the highest percentage of expenditure on health in 2015 and what was it?,"In 2015, Albania had the highest percentage expenditure on health, at 364.9752287%",The country with the highest percentage of expenditure on health in 2015 was Afghanistan with 8.16%.
6,What was the BMI in Togo in 2008?,The BMI of adults in Togo in 2008 was exceptionally low at 2.4.,BMI in Togo in 2008: 2.4
7,Which country had the maximum improvement in life expectancy between the years 2000 and 2015?,Haiti showed the greatest improvement in life expectancy between 2000 and 2015.,"The country with the maximum improvement in life expectancy between the years 2000 and 2015 is Belgium. The life expectancy in Belgium increased from 77.5 years in 2000 to 80.7 years in 2015, an increase of 3.2 years. This is a significant improvement in life expectancy, and it is a testament to the country's commitment to improving the health and well-being of its citizens. Belgium's success in improving life expectancy is a result of a"
8,What is the mean of infant deaths in South Sudan in the dataset?,The mean number of infant deaths per 1000 in South Sudan across all years in the dataset was 27.75.,The mean of infant deaths in South Sudan is 27.75.
9,Which are the unique countries where status is developed?,"The unique countries are Australia, Austria, Belgium, Bulgaria, Croatia, Cyprus, Czechia, Denmark, Germany, Hungary, Iceland, Ireland, Italy, Japan, Latvia, Lithuania, Luxembourg, Malta, Netherlands, New Zealand, Norway, Poland, Portugal, Romania, Singapore, Slovakia, Slovenia, Spain, Sweden, Switzerland, United Kingdom of Great Britain and Northern Ireland, United States of America.","The unique countries where status is developed are: Australia, Austria, Belgium, Bulgaria, Croatia, Cyprus, Czechia, Denmark, Germany, Hungary, Iceland, Ireland, Italy, Japan, Latvia, Lithuania, Luxembourg, Malta, Netherlands, New Zealand, Norway, Poland, Portugal, Romania, Singapore, Slovakia, Slovenia, Spain, Sweden, Switzerland, United Kingdom of Great Britain and Northern Ireland, United States of America"